# Generated by Django 4.2.1 on 2024-12-30 01:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
